language: python

python:
  - "3.5"

before_install:
  - npm install -g npm

script:
  - git config --global user.email "sillygod@livemail.tw"
  - git config --global user.name "sillygod"
  - git clone https://$GH_TOKEN@github.com/sillygod/sillygod.github.io.git output

after_success:
  - cd output
  - git checkout develop
  - npm install
  - ./node_modules/.bin/hexo g --debug
  - git checkout master
  - git pull origin master
  - rm -rf !(public)
  - mv public/* .
  - git add .
  - git commit -m "update from travis ci"
  - git push --quiet origin master
